Visualizing ChromHMM

Collaboration with https://github.com/jcrada

*** TODOs

- Add parameter heatmaps to label/coverage plot?
- Add different random initializations. How much does the model
  likelihood, accuracy and state assignment change between different
  random seeds?
- Add iteration parameter? Is is possible to obtain predictions at
  every genomic position for every iteration?

*** 3 Nov 2015

http://bl.ocks.org/tdhock/raw/2120199e9576d3628537/
- plot convergence metrics of last iteration. Likelihood is not
  increasing with the number of states!

*** 2 Nov 2015
http://bl.ocks.org/tdhock/raw/f24d410dd38e82a8eb70/
- added coverage data plot for one/several genomic regions.
- added selector for number of states.
- It is clear that the high false positive rate is due to 
  using the bad default macs peaks as input to ChromHMM.

*** 29 Oct 2015

Read txt files to iterations.RData.

Data viz with 1 interaction variable (iteration) 

http://bl.ocks.org/tdhock/raw/8db1f75d2595e0a570f9/
